// Package api は、アプリケーション全体が使う chi.Mux を組み立てる:
// グローバルミドルウェア、ヘルスチェック、Swagger UI、そして各 Feature の
// ルートを /api 配下にマウントする。
package api

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
	"gorm.io/gorm"

	_ "github.com/st-man-hori/go-feature-template/docs" // swagger docs, generated by `make openapi`
	"github.com/st-man-hori/go-feature-template/internal/features/task"
)

// NewRouter は HTTP 層全体を組み立てる。
//
// Laravel比較: bootstrap/app.php の withRouting()/withMiddleware() と
// routes/api.php を合わせた役割を果たす。この template は API 専用なので
// "web" と "api" のミドルウェアグループを分ける必要が無く、また
// ForceJsonRequest/CamelCaseJsonResponse に対応する Go 側の仕組みも無い:
// Handler は最初から JSON しか書かないし、`json` 構造体タグがそのまま wire 上の
// キーになるので、後からフレームワーク側で snake_case を変換する層が要らない。
func NewRouter(db *gorm.DB) *chi.Mux {
	r := chi.NewRouter()

	r.Use(middleware.RequestID)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	// Laravel の `health: '/up'` ルーティングオプションに相当。
	r.Get("/up", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
	})

	r.Get("/swagger/*", httpSwagger.WrapHandler)

	r.Route("/api", func(r chi.Router) {
		taskHandler := task.NewHandler(task.NewUseCase(db))
		task.RegisterRoutes(r, taskHandler)
	})

	return r
}
