// Package api assembles the chi.Mux the whole application serves: global
// middleware, the health check, Swagger UI, and every Feature's routes
// mounted under /api.
package api

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
	"gorm.io/gorm"

	_ "github.com/st-man-hori/go-feature-template/docs" // swagger docs, generated by `make openapi`
	"github.com/st-man-hori/go-feature-template/internal/features/task"
)

// NewRouter wires up the whole HTTP layer.
//
// Laravel comparison: this plays the role of bootstrap/app.php's
// withRouting()/withMiddleware() plus routes/api.php. There's no separate
// "web" vs "api" middleware group because this template is API-only, and
// ForceJsonRequest/CamelCaseJsonResponse have no Go equivalent here:
// handlers only ever write JSON, and `json` struct tags already control
// field casing on the wire, so there's no framework-level snake_case to
// translate after the fact.
func NewRouter(db *gorm.DB) *chi.Mux {
	r := chi.NewRouter()

	r.Use(middleware.RequestID)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	// Mirrors Laravel's `health: '/up'` routing option.
	r.Get("/up", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
	})

	r.Get("/swagger/*", httpSwagger.WrapHandler)

	r.Route("/api", func(r chi.Router) {
		taskHandler := task.NewHandler(task.NewUseCase(db))
		task.RegisterRoutes(r, taskHandler)
	})

	return r
}
